### ISSUE TITLE
Infinity rate result

### ISSUE THREAD

**Issue by vicentllongo** [okulik/lfconvert#1]
When I try to get the exchange rate for this day:
```
$ lfconvert -a 123.45 -d 2000-04-22
```
I get this output in the command line:
```
123.45 USD was on 2000-04-21 -Infinity EUR (at rate -0.0)
```

**Comment by okulik** [comment]
Good catch! I should have been more stringent about ingesting conversion rates data...

**Comment by okulik** [comment]
Fixed in https://github.com/okulik/lfconvert/commit/c6498ee2657c1b3d8ae6748e7f8c49be8439d0fa.
